version : '3.6'

services:
 db:
   image: postgres
   restart: always
   environment:
     POSTGRES_PASSWORD: 1234
 app:
   image : img1:1.0
   environment:
     IP: 0.0.0.0
     PORT: 8000
     POSTGRES_URL: db
     POSTGRES_PASSWORD: 1234
     
     